name: Build and deploy Node.js app to Azure Web App - virtualcenter

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies and build
        run: |
          npm ci
          npm run build

      - name: Zip build output (only dist, package.json, etc.)
        run: |
          mkdir deploy
          cp -r dist deploy/dist
          cp package*.json deploy/
          cd deploy && zip -r ../release.zip . && cd ..

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact
        run: unzip release.zip -d .

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_466CFA575EBC40879FCF5CBCE7132B71 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_51A848906886414A9D42D4562D5DF34D }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_69E5532242974EB4A57FAD74368E3C14 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'virtualcenter'
          slot-name: 'Production'
          package: .
